---
- name: Update and upgrade system packages
  hosts: all
  become: true
  tasks:

    - name: Update package cache (APT systems)
      apt:
        update_cache: yes
        when: ansible_os_family == "Debian"

    - name: Upgrade packages (APT systems)
      apt:
        upgrade: dist
        autoremove: yes
        when: ansible_os_family == "Debian"

    - name: Update all packages (RHEL/CentOS/Fedora systems)
      yum:
        name: "*"
        state: latest
        when: ansible_os_family == "RedHat"

    - name: Update all packages (DNF systems)
      dnf:
        name: "*"
        state: latest
        when: ansible_pkg_mgr == "dnf"
